Feature/live documentation
uni-bremen-agst/SEE pull request #626
Opened 2023-07-22 20:14 UTC by hlkuss

LiveDocumentation is a feature which allows SEE to display the documentation of classes and methods.

Links in the documentation are also represented as clickable links in the LiveDocumentation which opens the corresponding class.

2023-08-17 12:25 UTC, koschke requested changes
I started to review this PR but ran into too many violations of our coding style. Please read our [style guide](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist), fix your code accordingly, and let me know when you are done.

Also, I noticed a compiler error:
`Assets\SEE\Utils\LiveDocumentation\CSharpExtractor.cs(122,25): error CS0103: The name 'ProcessReturnTag' does not exist in the current context`

Always make sure your code compiles before creating a pull request.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/City/NodeScalingAnimator.cs
> +    public class NodeScalingAnimator : MonoBehaviour
What's the purpose of a `NodeScalingAnimator`? All animation must be handled by `NodeOperator`.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +            var builder = new StringBuilder();
Do not use `var`.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +    ///     LiveDocumentationBuffer contains the documentation of a class including links as chunks of
Fix indentation.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +        ///     Constructor for the <see cref="LiveDocumentationBuffer" />
Fix indentation. All comments should be indented uniformely to the rest of our code.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +            BufferItems = new List<ILiveDocumentationBufferItem>();
Assignment can be done at the declaration of this property.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +            var builder = new StringBuilder();
Use simplified `new` operator.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +            foreach (var i in BufferItems) builder.Append(i.GetPrintableText());
Do not use `var`. Always use brackets.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +            foreach (var i in BufferItems) builder.Append(i.GetPrintableText());
Instead of `i` (reserved for integer indices), use `item`.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +        ///     Prints the entire buffer with all it's elements concatenated together.
_its_ not _it's_

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +    ///     LiveDocumentationBuffer contains the documentation of a class including links as chunks of
I fixed it.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +        ///     Constructor for the <see cref="LiveDocumentationBuffer" />
I fixed it.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +            BufferItems = new List<ILiveDocumentationBufferItem>();
I fixed it.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +        ///     Prints the entire buffer with all it's elements concatenated together.
I fixed it.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +            var builder = new StringBuilder();
I fixed it.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +            var builder = new StringBuilder();
I fixed it.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +            foreach (var i in BufferItems) builder.Append(i.GetPrintableText());
I fixed it.

2023-08-17 12:25 UTC, koschke commented on Assets/SEE/Game/UI/LiveDocumentation/Buffer/LiveDocumentationBuffer.cs
> +            foreach (var i in BufferItems) builder.Append(i.GetPrintableText());
I fixed it.

2023-08-17 12:28 UTC, koschke commented
@hlkuss @KritikoAlex There are too many instances of trailing whitespace in your code.

Do not use trailing whitespace at the end of a line. Trailing whitespace is unnecessary and is a source of potential merge conflicts and superflous code differences. There is a plug-in for visual studio named [RemoveTrailingWhitespaces](https://marketplace.visualstudio.com/items?itemName=Predelnik.RemoveTrailingWhitespaces2019) that removes trailing whitespace when a file is saved.

2023-08-24 21:02 UTC, hlkuss commented
I've resolved the issues.

Please apologize for the inconvenience, I've totally forgotten about the style guide.

2023-08-25 18:19 UTC, koschke commented
> I've resolved the issues.
> 
> Please apologize for the inconvenience, I've totally forgotten about the style guide.

Thanks for the moment. I will take a look when I am back home again.

2024-05-10 10:12 UTC, koschke commented
We will not merge this PR in the master. Our new LSP integration will supersede it.

2024-05-10 10:12 UTC, closed without merging