654 embedded browser lysander
uni-bremen-agst/SEE pull request #658
Opened 2023-11-07 11:51 UTC by lilSander

This is the final implementation of the embedded-browser in SEE.

2023-11-07 13:28 UTC, koschke requested changes
There were files checked in that should not have been checked in. I removed them from the history. Please be careful on what to check in and better ask if in doubt.

TVAction.cs must be moved to an appropriate place.

2023-11-07 13:28 UTC, koschke commented on Assets/TVAction.cs
Must be contained at an appropriate place in the SEE folder and be enclosed in a namespace accordingly. See https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist

Use `git mv` instead of the move command of your operating system.

2023-11-07 13:28 UTC, koschke commented on Assets/TVAction.cs.meta
Must be moved along with the file `TVAction.cs`. Use `git mv` instead of the move command of your operating system.

2023-11-07 13:37 UTC, koschke requested changes

2023-11-07 13:37 UTC, koschke commented on Assets/TVAction.cs
> +
This class must be documented and be nested in a namespace.

2023-11-07 14:41 UTC, lilSander commented on Assets/TVAction.cs
> +            for (int i=0;i<=4;i++)
But when I disable the parent (BrowserCanvas), then I also disable this script, because it is a component of the BrowserCanvas.

2023-11-09 08:35 UTC, koschke approved these changes
All fine now. I renamed the class because class name and filename must be identical
and improved the documentation a bit.

2023-11-09 12:29 UTC, falko17 commented
It seems the test is failing due to the dashboard's supported version being out-of-date with the actual Dashboard version (hosted at `stvr2`). I think it's unnecessary for the test to check for the exact version, so I'll modify it such that only the major and minor version (e.g., 6.5) is compared.

![image](https://github.com/uni-bremen-agst/SEE/assets/10247603/c577d119-f425-4b24-9d89-658940bcd7b2)

2023-11-09 14:00 UTC, merged