TreeView: Filtering, Sorting, Grouping
uni-bremen-agst/SEE pull request #681
Opened 2023-12-09 22:25 UTC by falko17

Apart from a lot of smaller improvements to the TreeWindow, this pull request adds the following functionality (accessible via buttons next to the search bar):
- **Filtering**: Both the normal tree view and the graph search can apply a combination of filters, handled by the `GraphFilter` class. Currently, this only includes toggle attributes and a toggle for edges. Filtered elements will not be shown in the TreeWindow (orphan nodes and dangling edges are "lifted" upwards).
- **Sorting**: Both the normal tree view and the graph search can sort the results by a number of attributes via the `GraphSorter` class. Currently, this includes the source name, the source line, the filename, and the type. Sorters are applied in order, and can be made descending or ascending on a case-by-case basis.
- **Grouping**: In the tree view, elements can be grouped together (i.e., put below a root node together) via the `TreeWindowGrouper` class. Currently, this is possible with the reflexion state and the element type. Only one group can be applied at a time. The hierarchy is preserved here – for details on what this means, see #680. Elements that do not actually belong to the group are rendered in italics.

All three modifiers can be combined in any desired way (e.g., filters can still be applied while grouping elements). Additionally, it should be very easy to include additional filters/sorters/groupers with this structure in place.

## Additional Changes
* A static `Icons` class has been added, so that icon glyphs can be easily reused across different contexts. See https://github.com/uni-bremen-agst/SEE/wiki/Icons for details.
* Headings for PopupMenus have been implemented.
* A bug in the MoveAction has been fixed that led to nodes not being unparented correctly in a reflexion analysis context.
* An option has been added to keep PopupMenus open even after clicking on them.
* A `DefaultDictionary` has been added that adds and returns a default value if an accessed dictionary key does not actually exist.
* A bug in the CI has been fixed which led to bad patterns not being detected correctly.
* Unity has been updated to version 2022.3.15f1.
* Additional smaller bug fixes.

2023-12-13 15:01 UTC, koschke requested changes
I have only very trivial remarks.

2023-12-13 20:39 UTC, falko17 commented on Assets/SEE/DataModel/GraphSearch/GraphFilter.cs
> +        // if empty, include all. otherwise, *at least one* must be present.
My bad, I forgot to delete this after writing proper documentation for this class. Deleted it now.

2023-12-13 20:40 UTC, falko17 commented on Assets/SEE/DataModel/DG/Graph.cs
>          /// Returns the names of all node types of this graph
Fixed.

2023-12-13 20:41 UTC, falko17 commented on Assets/SEE/DataModel/DG/Graph.cs
> +        /// Returns the names of all edge types of this graph
Fixed.

2023-12-13 20:41 UTC, falko17 commented on Assets/SEE/DataModel/DG/Graph.cs
> +        /// Returns the names of all element types of this graph
Fixed.

2023-12-13 20:43 UTC, falko17 commented on Assets/SEE/Utils/CollectionExtensions.cs
> +    public static class CollectionExtensions
Fixed.

2023-12-13 20:43 UTC, falko17 commented on Assets/SEE/DataModel/GraphSearch/GraphSorter.cs
> +
Fixed.

2023-12-13 20:44 UTC, falko17 commented on Assets/SEE/DataModel/GraphSearch/GraphSearch.cs
> +        private IEnumerable<IGraphModifier> Modifiers => new IGraphModifier[] { Filter, Sorter };
Yes, I added it now.

2023-12-14 09:18 UTC, koschke commented on Assets/SEE/UI/Window/TreeWindow/TreeWindowContextMenu.cs
> +            // TODO: Any other attributes we want to sort by? Or should we just include all attributes in the future?
Didn't know that was a question to me.

These are the attributes we want to sort by for the time being. We might want to include all other attributes in the future, in which case the code can be adapted. Let's wait and see whether a need for that arises at all.

I turned my review comment into a code comment and removed the TODO.

2023-12-14 09:22 UTC, koschke commented on Assets/SEE/UI/Window/TreeWindow/TreeWindowContextMenu.cs
> +                // TODO: Any other useful groups?
Didn't know that was a question to me.

As above, let's wait and see whether we need additional grouping criteria. I removed the TODO and added a code comment:

```
// Here we define the criteria by which a user can group. If new grouping criteria
// arise in the future, they need to be added here.
```

2023-12-14 09:24 UTC, koschke commented on Assets/SEE/DataModel/GraphSearch/GraphFilter.cs
> +        public bool IsActive() => !IncludeNodes || !IncludeEdges
I added a <see cref=...> reference to the interface method implemented.

2023-12-14 09:24 UTC, koschke commented on Assets/SEE/DataModel/GraphSearch/GraphFilter.cs
> +        public void Reset()
I added a <see cref=...> reference to the interface method implemented.

2023-12-14 09:26 UTC, koschke commented on Assets/SEE/DataModel/GraphSearch/GraphSorter.cs
> +        public void Reset() => SortAttributes.Clear();
I added a <see cref=...> reference to the interface method implemented.

2023-12-14 09:26 UTC, koschke commented on Assets/SEE/DataModel/GraphSearch/GraphSorter.cs
> +        public bool IsActive() => SortAttributes.Count > 0;
I added a <see cref=...> reference to the interface method implemented.

2023-12-14 12:00 UTC, koschke approved these changes
All fine. I resolved all remaining issues myself.

2023-12-14 12:08 UTC, merged