723 Git Metrics in Diff City
uni-bremen-agst/SEE pull request #731
Opened 2024-05-05 17:37 UTC by Omidious

We want to be able to see Git metrics like commit frequency, number of code added and deleted, etc. in Diff City when we generate a city. Use GitGraphProvider in Diff City in combination with VCSGraphProvider to generate Git metrics. Enter the required information under the VCS tab.

2024-05-09 14:38 UTC, falko17 commented
Before I review this, how does this relate to #730? Does it directly depend on it, i.e., should #730 be merged first?

2024-05-09 14:52 UTC, Omidious commented
> Before I review this, how does this relate to #730? Does it directly depend on it, i.e., should #730 be merged first?
GitGraphProvider uses VCSGraphProvider in #730 to add Git metrics to a graph generated from a Git repository via VCSGraphProvider. I think it would be better if #730 was merged first.

2024-05-09 17:20 UTC, koschke requested changes
Overall, this looks good. I have only minor change requests.

- Do not use 'var' (except for rare exceptions where not using it would render the code less readable).
- Metric names must start with prefix `Metric.` and must not contain blanks. Consider to define the names in `SEE.DataModel.DG.StandardNames.cs`

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +    /// Calculates metrics between 2 revisions from a git repository and adds these to a graph.
Numbers until (including) twelve are generally given in words. So, "2" should be replaced by "two".

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +        /// Calculates metrics between 2 revisions from a git repository and adds these to <paramref name="graph"/>.
Numbers until (including) twelve are generally given in words. So, "2" should be replaced by "two".

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var oldCommit = repo.Lookup<Commit>(oldRevision);
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var newCommit = repo.Lookup<Commit>(newRevision);
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var changes = repo.Diff.Compare<Patch>(oldCommit.Tree, newCommit.Tree);
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                foreach (var change in changes)
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                    foreach (var node in graph.Nodes())
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +            using (var repo = new Repository(vcsPath))
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var oldCommit = repo.Lookup<Commit>(oldRevision);
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var commits = repo.Commits.QueryBy(new CommitFilter { SortBy = CommitSortStrategies.Topological });
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                foreach (var commit in commits)
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                        foreach (var parent in commit.Parents)
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                                var filePath = change.Path;
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                                var id = commit.Author.Email;
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                foreach (var entry in uniqueContributorsPerFile)
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var oldCommit = repo.Lookup<Commit>(oldRevision);
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var newCommit = repo.Lookup<Commit>(newRevision);
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var commitsBetween = repo.Commits.QueryBy(new CommitFilter
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                Dictionary<string, int> fileCommitCounts = new Dictionary<string, int>();
You can use the simpler `new()` operator.

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                foreach (var commit in commitsBetween)
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                    foreach (var parent in commit.Parents)
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                        var changes = repo.Diff.Compare<TreeChanges>(parent.Tree, commit.Tree);
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                            var filePath = change.Path;
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                            if (fileCommitCounts.ContainsKey(filePath))
All code in bodies of control statement must be nested in curly brackets.

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                foreach (var entry in fileCommitCounts.OrderByDescending(x => x.Value))
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                    foreach (var node in graph.Nodes())
[Do not use `var`.](https://github.com/uni-bremen-agst/SEE/wiki/ReviewChecklist)

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                            node.SetInt("Commit Frequency", entry.Value);
Metric names must start with prefix `Metric.` and must not contain blanks.

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                            node.SetInt("Number of Developers", entry.Value.Count);
Metric names must start with prefix `Metric.` and must not contain blanks.

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                            node.SetInt("Lines Added", change.LinesAdded);
Metric names must start with prefix `Metric.` and must not contain blanks.

2024-05-09 17:20 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                            node.SetInt("Lines Deleted", change.LinesDeleted);
Metric names must start with prefix `Metric.` and must not contain blanks.

2024-05-11 16:02 UTC, Omidious commented
I applied the changes requested by the reviewers.

2024-05-19 17:34 UTC, koschke requested changes
Looks good.

Could you also provide test cases? Thanks!

2024-05-19 17:35 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +    /// Calculates metrics between 2 revisions from a git repository and adds these to a graph.
Was fixed.

2024-05-19 17:35 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +        /// Calculates metrics between 2 revisions from a git repository and adds these to <paramref name="graph"/>.
Was fixed.

2024-05-19 17:35 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var newCommit = repo.Lookup<Commit>(newRevision);
Was fixed.

2024-05-19 17:36 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var changes = repo.Diff.Compare<Patch>(oldCommit.Tree, newCommit.Tree);
Was fixed.

2024-05-19 17:38 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                            node.SetInt("Commit Frequency", entry.Value);
Was fixed.

2024-05-19 17:38 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                    foreach (var node in graph.Nodes())
Was fixed.

2024-05-19 17:38 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                            node.SetInt("Lines Added", change.LinesAdded);
Was fixed.

2024-05-19 17:38 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                            node.SetInt("Lines Deleted", change.LinesDeleted);
Was fixed.

2024-05-19 17:38 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var oldCommit = repo.Lookup<Commit>(oldRevision);
Was fixed.

2024-05-19 17:38 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                foreach (var change in changes)
Was fixed.

2024-05-19 17:39 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +            using (var repo = new Repository(vcsPath))
Was fixed.

2024-05-19 17:39 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var commits = repo.Commits.QueryBy(new CommitFilter { SortBy = CommitSortStrategies.Topological });
Was fixed.

2024-05-19 17:40 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                Dictionary<string, int> fileCommitCounts = new Dictionary<string, int>();
Was fixed.

2024-05-19 17:40 UTC, koschke commented on Assets/SEE/GraphProviders/GitGraphProvider.cs
> +                var commitsBetween = repo.Commits.QueryBy(new CommitFilter
Was fixed.

2024-05-19 17:41 UTC, koschke commented
Please mark all suggestions you addressed as resolved.

2024-05-29 12:31 UTC, Omidious commented
I added the requested test cases for GitGraphProvider

2024-06-14 13:53 UTC, merged