717 Taking notes associated with nodes and edges
uni-bremen-agst/SEE pull request #748
Opened 2024-07-01 17:06 UTC by TimDinh-hub

This pull request introduces a new note management feature that allows users to create, edit, extend, delete, and toggle visibility of notes for selected nodes and edges. Additionally, notes can be saved and loaded, and they support both private and public visibility modes. The following functionalities are included:

- Create and manage notes:
  - The user can create a note by right-clicking on a node/edge and pressing "Create note".
  - By creating a new note, the node/edge will be marked with an outline.
  - If a note already exists, the saved content is loaded.
  - When the user opens a note window, a new window with 5 buttons appears on the side:
    1. Save button - Save the content to a file.
    2. Load button - Load the content from a file to the currently active note window.
    3. Delete button - Deletes the content.
    4. Refresh button - Loads the new content if it got change by another client.
    5. Toggle button - A toggle button to specify if you want the note public or private.
- Toggle Note Visibility:
  - The user can choose to show or hide the outlines of the nodes/edges by changing their Action to "Note"
  - You can either click the middle mouse button to hide/show all the outlines. Alternatively you can click on the nodes/edges one by one.

2024-07-02 12:31 UTC, koschke requested changes
Please revert all your accidental changes in `Assets/Plugins` and `Assets/Resources`.

Apparently, you have branched from branch `whiteboard`. Now your own additions are burried in the list of the changes made by @Cyclone1337. The branch `whiteboard` is still work in progress. I would prefer to merge your branch after branch `whiteboard` is merged.

2024-07-02 12:31 UTC, koschke commented on .vsconfig
This file must not be added. Please remove it again.

2024-07-02 12:31 UTC, koschke commented on Assets/Plugins/AmplifyShaderEditor/Examples/Built-In/Community Skybox Cubemap Extended/Meshes/Materials/01 - Default.mat
Please revert all your accidental changes in Assets/Plugins and Assets/Resources.

2024-07-04 14:36 UTC, TimDinh-hub commented on Assets/Plugins/AmplifyShaderEditor/Examples/Built-In/Community Skybox Cubemap Extended/Meshes/Materials/01 - Default.mat
fixed

2024-07-04 16:52 UTC, TimDinh-hub commented on Assets/SEE/UI/Window/NoteWindow/NoteButtonWindow.cs
> +            Destroy(buttonWindow);
fixed

2025-05-19 08:35 UTC, koschke commented
Will not be merged.

2025-05-19 08:35 UTC, closed without merging