Remove rotate resize actions
uni-bremen-agst/SEE pull request #804
Opened 2024-10-29 09:26 UTC by tinxx

This MR removes the now obsolete actions for scaling and rotating a node.

The resize node action has been improved to allow for resize on the up-axis. Additionally, sprite handles now indicate the resize direction with a dedicated shader that honors portals.

![screenshot-2024-10-29-09-22-29](https://github.com/user-attachments/assets/2dee9964-2ef5-486a-8e6f-7c903f18376a)

Background:
As node dimensions are usually derived from code metrics, rotation and resize are generally not a good idea.
However, there are exceptions that can be flagged to `AllowManualResize`. These are, as of now, the architecture nodes that need to be resized to allow for other nodes to be placed on them.

2024-10-29 16:54 UTC, falko17 requested changes
Thanks, it's always nice to get a PR where thousands of lines can be deleted :D
Just a few comments below, but all of them are minor.

2024-10-29 16:54 UTC, falko17 commented on Assets/Resources/Shaders/TransparentSpritePortalShader.shader
> +        _MainTex ("Texture", 2D) = "white" {}
There probably shouldn't be a space here:
```suggestion
        _MainTex("Texture", 2D) = "white" {}
```

2024-10-29 16:54 UTC, falko17 commented on Assets/Resources/Shaders/TransparentSpritePortalShader.shader
> +            "IgnoreProjector"="True"
Consistent formatting with the rest here:
```suggestion
            "Queue" = "Transparent"
            "RenderType" = "Transparent"
            "IgnoreProjector" = "True"
```

2024-10-29 16:54 UTC, falko17 commented on Assets/SEE/Controls/Actions/ActionStateTypes.cs
General comment: It seems that some tests are failing, probably due to the changes in this class. Please investigate and fix this.

2024-10-29 16:54 UTC, falko17 commented on Assets/SEE/Controls/Actions/ResizeNodeAction.cs
> +                mainCameraTransform = Camera.main.transform;
I think we already have a cached field for this in `MainCamera.cs`.

2024-10-29 16:54 UTC, falko17 commented on Assets/SEE/Controls/Actions/ResizeNodeAction.cs
> +                        0.5001f * directionToCamera.x,
This `0.5001f` magic number is repeated a few times in this file, can you extract it into a named constant?

2024-10-29 16:54 UTC, falko17 commented on Assets/SEE/Controls/Actions/ResizeNodeAction.cs
> +                    cursorMovement = new(0f, (currentResizeStep.InitialMousePosition.y - Input.mousePosition.y) / Screen.height, 0f);
Can this method also be called on VR players? If so, we cannot use the mouse position/screen height.

2024-10-29 16:54 UTC, falko17 commented on Assets/SEE/Controls/Actions/ResizeNodeAction.cs
> +                                child.localPosition.x + (shift2D ? 0.5f * posDiff.x * currentResizeStep.Direction.x: 0f),
```suggestion
                                child.localPosition.x + (shift2D ? 0.5f * posDiff.x * currentResizeStep.Direction.x : 0f),
```

2024-10-29 16:54 UTC, falko17 commented on Assets/SEE/Controls/Actions/ResizeNodeAction.cs
> +                                child.localPosition.y + posDiff.y, // we always resize height in positiove direction
```suggestion
                                child.localPosition.y + posDiff.y, // we always resize height in positive direction
```

2024-10-29 16:54 UTC, falko17 commented on Assets/SEE/Game/City/VisualNodeAttributes.cs
> +        [Tooltip("May users resize this type of node?.")]
```suggestion
        [Tooltip("May users resize this type of node?")]
```

2024-10-29 16:54 UTC, falko17 commented on Assets/SEE/Game/SceneManipulation/GameNodeMover.cs
> +        /// Empty space on the y-axis bewteen the top of the target object and the bottom of the child
```suggestion
        /// Empty space on the y-axis between the top of the target object and the bottom of the child
```

2024-10-29 16:54 UTC, falko17 commented on Assets/SEE/GameObjects/Materials.cs
> +        private const string spriteName = "Materials/TransparentSpritePortalMaterial";
Field should ideally be named `spriteMaterialName` (like the others above it).

2024-10-30 20:01 UTC, falko17 commented on Assets/SEE/Controls/Actions/ResizeNodeAction.cs
> +                    cursorMovement = new(0f, (currentResizeStep.InitialMousePosition.y - Input.mousePosition.y) / Screen.height, 0f);
I've added an issue #806 which tracks this problem, so we can merge this before handling that part.

2024-10-31 08:16 UTC, tinxx commented
> Apart from the compile error, this looks good to me now and can be merged! I'll enable auto-merge, so as soon as the pipeline runs through (i.e., the error is fixed) this should be done.

I have removed the VR code paths for rotate as well.  However, I currently cannot test VR at all but this fixes the
compilation errors.

I think we need someone to test VR regularly because most developers won't be able to do that.

2024-10-31 08:44 UTC, merged